/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerShopIndexRouteImport } from './routes/_customer.shop.index'
import { Route as CustomerShopWishlistRouteImport } from './routes/_customer.shop.wishlist'
import { Route as CustomerShopSettingsRouteImport } from './routes/_customer.shop.settings'
import { Route as CustomerShopProfileRouteImport } from './routes/_customer.shop.profile'
import { Route as CustomerShopProductsRouteImport } from './routes/_customer.shop.products'
import { Route as CustomerShopOrdersRouteImport } from './routes/_customer.shop.orders'
import { Route as CustomerShopCheckoutRouteImport } from './routes/_customer.shop.checkout'
import { Route as CustomerShopCartRouteImport } from './routes/_customer.shop.cart'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin.admin.products'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin.admin.payments'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin.admin.orders'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminInventoryRouteImport } from './routes/_admin.admin.inventory'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin.admin.customers'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin.analytics'
import { Route as CustomerShopProductsProductIdRouteImport } from './routes/_customer.shop.products_.$productId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerShopIndexRoute = CustomerShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopWishlistRoute = CustomerShopWishlistRouteImport.update({
  id: '/shop/wishlist',
  path: '/shop/wishlist',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopSettingsRoute = CustomerShopSettingsRouteImport.update({
  id: '/shop/settings',
  path: '/shop/settings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopProfileRoute = CustomerShopProfileRouteImport.update({
  id: '/shop/profile',
  path: '/shop/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopProductsRoute = CustomerShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopOrdersRoute = CustomerShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopCheckoutRoute = CustomerShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopCartRoute = CustomerShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInventoryRoute = AdminAdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerShopProductsProductIdRoute =
  CustomerShopProductsProductIdRouteImport.update({
    id: '/shop/products_/$productId',
    path: '/shop/products/$productId',
    getParentRoute: () => CustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/shop/cart': typeof CustomerShopCartRoute
  '/shop/checkout': typeof CustomerShopCheckoutRoute
  '/shop/orders': typeof CustomerShopOrdersRoute
  '/shop/products': typeof CustomerShopProductsRoute
  '/shop/profile': typeof CustomerShopProfileRoute
  '/shop/settings': typeof CustomerShopSettingsRoute
  '/shop/wishlist': typeof CustomerShopWishlistRoute
  '/shop/': typeof CustomerShopIndexRoute
  '/shop/products/$productId': typeof CustomerShopProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/shop/cart': typeof CustomerShopCartRoute
  '/shop/checkout': typeof CustomerShopCheckoutRoute
  '/shop/orders': typeof CustomerShopOrdersRoute
  '/shop/products': typeof CustomerShopProductsRoute
  '/shop/profile': typeof CustomerShopProfileRoute
  '/shop/settings': typeof CustomerShopSettingsRoute
  '/shop/wishlist': typeof CustomerShopWishlistRoute
  '/shop': typeof CustomerShopIndexRoute
  '/shop/products/$productId': typeof CustomerShopProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/inventory': typeof AdminAdminInventoryRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_customer/shop/cart': typeof CustomerShopCartRoute
  '/_customer/shop/checkout': typeof CustomerShopCheckoutRoute
  '/_customer/shop/orders': typeof CustomerShopOrdersRoute
  '/_customer/shop/products': typeof CustomerShopProductsRoute
  '/_customer/shop/profile': typeof CustomerShopProfileRoute
  '/_customer/shop/settings': typeof CustomerShopSettingsRoute
  '/_customer/shop/wishlist': typeof CustomerShopWishlistRoute
  '/_customer/shop/': typeof CustomerShopIndexRoute
  '/_customer/shop/products_/$productId': typeof CustomerShopProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/orders'
    | '/shop/products'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/wishlist'
    | '/shop/'
    | '/shop/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/orders'
    | '/shop/products'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/wishlist'
    | '/shop'
    | '/shop/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_customer'
    | '/login'
    | '/unauthorized'
    | '/_admin/admin/analytics'
    | '/_admin/admin/customers'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/inventory'
    | '/_admin/admin/notifications'
    | '/_admin/admin/orders'
    | '/_admin/admin/payments'
    | '/_admin/admin/products'
    | '/_admin/admin/reports'
    | '/_admin/admin/settings'
    | '/_customer/shop/cart'
    | '/_customer/shop/checkout'
    | '/_customer/shop/orders'
    | '/_customer/shop/products'
    | '/_customer/shop/profile'
    | '/_customer/shop/settings'
    | '/_customer/shop/wishlist'
    | '/_customer/shop/'
    | '/_customer/shop/products_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/shop/': {
      id: '/_customer/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof CustomerShopIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/wishlist': {
      id: '/_customer/shop/wishlist'
      path: '/shop/wishlist'
      fullPath: '/shop/wishlist'
      preLoaderRoute: typeof CustomerShopWishlistRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/settings': {
      id: '/_customer/shop/settings'
      path: '/shop/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof CustomerShopSettingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/profile': {
      id: '/_customer/shop/profile'
      path: '/shop/profile'
      fullPath: '/shop/profile'
      preLoaderRoute: typeof CustomerShopProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/products': {
      id: '/_customer/shop/products'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof CustomerShopProductsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/orders': {
      id: '/_customer/shop/orders'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof CustomerShopOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/checkout': {
      id: '/_customer/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof CustomerShopCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/shop/cart': {
      id: '/_customer/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof CustomerShopCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory': {
      id: '/_admin/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminAdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/shop/products_/$productId': {
      id: '/_customer/shop/products_/$productId'
      path: '/shop/products/$productId'
      fullPath: '/shop/products/$productId'
      preLoaderRoute: typeof CustomerShopProductsProductIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminInventoryRoute: typeof AdminAdminInventoryRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminInventoryRoute: AdminAdminInventoryRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerShopCartRoute: typeof CustomerShopCartRoute
  CustomerShopCheckoutRoute: typeof CustomerShopCheckoutRoute
  CustomerShopOrdersRoute: typeof CustomerShopOrdersRoute
  CustomerShopProductsRoute: typeof CustomerShopProductsRoute
  CustomerShopProfileRoute: typeof CustomerShopProfileRoute
  CustomerShopSettingsRoute: typeof CustomerShopSettingsRoute
  CustomerShopWishlistRoute: typeof CustomerShopWishlistRoute
  CustomerShopIndexRoute: typeof CustomerShopIndexRoute
  CustomerShopProductsProductIdRoute: typeof CustomerShopProductsProductIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerShopCartRoute: CustomerShopCartRoute,
  CustomerShopCheckoutRoute: CustomerShopCheckoutRoute,
  CustomerShopOrdersRoute: CustomerShopOrdersRoute,
  CustomerShopProductsRoute: CustomerShopProductsRoute,
  CustomerShopProfileRoute: CustomerShopProfileRoute,
  CustomerShopSettingsRoute: CustomerShopSettingsRoute,
  CustomerShopWishlistRoute: CustomerShopWishlistRoute,
  CustomerShopIndexRoute: CustomerShopIndexRoute,
  CustomerShopProductsProductIdRoute: CustomerShopProductsProductIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
