name: 'Deploy App'

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest # Self hosted nodes 
    strategy:
      matrix:
        service: [auth-service, cart-service, inventory-service, notification-service, order-service, payment-service, product-service]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build and Package
      run: |
        cd ${{ matrix.service }}
        mkdir -p package
        pip install --platform manylinux2014_x86_64 --target=package --implementation cp --python-version 3.11 --only-binary=:all: --upgrade -r requirements.txt
        rm -rf package/botocore
        rm -rf package/boto3
        rm -rf package/botocore
        cp -r *.py package/ || true
        cp -r routers package/ || true
        cp -r schemas package/ || true
        cp -r services package/ || true
        cp -r clients package/ || true
        cp -r repositories package/ || true
        cp -r utils package/ || true
        cd package
        zip -r ../${{ matrix.service }}.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name angadi-hub-${{ matrix.service }} \
          --zip-file fileb://${{ matrix.service }}/${{ matrix.service }}.zip


