name: 'Hotfix IAM Policy'

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/hotfix_iam.yml'

jobs:
  fix-iam:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Attach DynamoDB Policy
      run: |
        aws iam attach-role-policy \
          --role-name angadi-hub-lambda-exec-role \
          --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
