name: DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk SCA (Dependency Scan)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, cart-service, inventory-service, notification-service, order-service, payment-service, product-service]
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=${{ matrix.service }}/requirements.txt --package-manager=pip
        continue-on-error: true # Prevent failing the whole build during testing

  sonarcloud-scan:
    name: SonarQube SAST (Code Analysis)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
